version: '2'
services:
  acmedns:
    image: joohoi/acme-dns:latest
    restart: always
    ports:
      - "443:443"
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./config:/etc/acme-dns:ro
      - ./data:/var/lib/acme-dns
